#!/bin/bash

# Insert Default Slack Channel & API Token Here
Slack_Channel="#YOUR_SLACK_CHANNEL_HERE"
Slack_API="YOUR_SLACK_LEGACY_TOKEN_HERE"

# Reads stdin and Passes to Slack API in Text Snippet
read -d '' stdin
if [ -z "$1" ]
then
channel=$Slack_Channel
else
channel=$1
fi

# Echoes to Terminal
echo $stdin

# Makes Curl Request to API
curl -s -F "content=$stdin" -F "channels=$channel" -F "title=Slack Stdout" -H "Authorization: Bearer $Slack_API" https://slack.com/api/files.upload > /dev/null
